In [2]:
import pandas as pd

In [3]:
prt = pd.read_csv('data/prt_monthly_ridership.csv')

In [4]:
prt.info()

<class 'pandas.DataFrame'>
RangeIndex: 26483 entries, 0 to 26482
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Route            26483 non-null  str
 1   Route_Full_Name  26281 non-null  str
 2   Current_Garage   26289 non-null  str
 3   Mode             26483 non-null  str
 4   Month_Start      26483 non-null  str
 5   Date_Key         26483 non-null  int64
 6   Day_Type         26483 non-null  str
 7   Avg_Riders       26483 non-null  float64
 8   Day_Count        26483 non-null  int64
dtypes: float64(1), int64(2), str(6)
memory usage: 1.8 MB

In [5]:
prt.head(10)

,Route,Route_Full_Name,Current_Garage,Mode,Month_Start,Date_Key,Day_Type,Avg_Riders,Day_Count
0,1,1 - FREEPORT ROAD,Ross,Bus,4/1/2026,202604,SAT.,1339.50,4
1,11,11 - FINEVIEW,Ross,Bus,4/1/2026,202604,SAT.,191.00,4
2,12,12 - MCKNIGHT,Ross,Bus,4/1/2026,202604,SAT.,1081.00,4
3,13,13 - BELLEVUE,Ross,Bus,4/1/2026,202604,SAT.,1310.25,4
4,14,14 - OHIO VALLEY,Ross,Bus,4/1/2026,202604,SAT.,348.75,4
5,15,15 - CHARLES,Ross,Bus,4/1/2026,202604,SAT.,600.50,4
6,16,16 - BRIGHTON,Ross,Bus,4/1/2026,202604,SAT.,1414.25,4
7,17,17 - SHADELAND,Ross,Bus,4/1/2026,202604,SAT.,388.50,4
8,2,2 - MOUNT ROYAL,Ross,Bus,4/1/2026,202604,SAT.,180.25,4
9,20,20 - KENNEDY,Collier,Bus,4/1/2026,202604,SAT.,280.50,4

In [6]:
prt.describe(include='all')

,Route,Route_Full_Name,Current_Garage,Mode,Month_Start,Date_Key,Day_Type,Avg_Riders,Day_Count
count,26483,26281,26289,26483,26483,26483.000000,26483,26483.000000,26483.000000
unique,111,103,6,3,112,NaN,3,NaN,NaN
top,1,1 - FREEPORT ROAD,East Liberty,Bus,4/1/2026,NaN,WEEKDAY,NaN,NaN
freq,336,336,7579,25118,250,NaN,11151,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,202132.174149,NaN,1145.557665,11.604916
std,NaN,NaN,NaN,NaN,NaN,269.007458,NaN,1321.945759,8.307031
min,NaN,NaN,NaN,NaN,NaN,201701.000000,NaN,-1.954545,3.000000
25%,NaN,NaN,NaN,NaN,NaN,201906.000000,NaN,327.925000,4.000000
50%,NaN,NaN,NaN,NaN,NaN,202110.000000,NaN,709.500000,5.000000
75%,NaN,NaN,NaN,NaN,NaN,202401.000000,NaN,1449.647727,21.000000
max,NaN,NaN,NaN,NaN,NaN,202604.000000,NaN,11510.250000,23.000000

In [7]:
for c in ['Route','Route_Full_Name','Current_Garage','Mode','Month_Start','Day_Type']:
    print(prt[c].value_counts(dropna=False).head(5))

Route
1     336
11    336
12    336
13    336
14    336
Name: count, dtype: int64
Route_Full_Name
1 - FREEPORT ROAD    336
11 - FINEVIEW        336
12 - MCKNIGHT        336
13 - BELLEVUE        336
14 - OHIO VALLEY     336
Name: count, dtype: int64
Current_Garage
East Liberty           7579
West Mifflin           6404
Ross                   5697
Collier                5254
South Hills Village    1042
Name: count, dtype: int64
Mode
Bus        25118
Rail        1052
Incline      313
Name: count, dtype: int64
Month_Start
4/1/2026     250
7/1/2024     247
6/1/2024     247
10/1/2025    245
7/1/2025     245
Name: count, dtype: int64
Day_Type
WEEKDAY    11151
SAT.        7837
SUN.        7495
Name: count, dtype: int64

In [8]:
prt_clean = prt.copy()

In [9]:
prt_clean.duplicated().sum()

np.int64(0)

In [10]:
key = ["Route", "Mode", "Month_Start", "Day_Type"]
prt_clean.duplicated(subset=key).sum()

np.int64(0)

In [11]:
prt_clean.dtypes

Route                  str
Route_Full_Name        str
Current_Garage         str
Mode                   str
Month_Start            str
Date_Key             int64
Day_Type               str
Avg_Riders         float64
Day_Count            int64
dtype: object

In [12]:
prt_clean["Mode"].value_counts(dropna=False)

Mode
Bus        25118
Rail        1052
Incline      313
Name: count, dtype: int64

In [13]:
prt_clean["Day_Type"].value_counts(dropna=False)

Day_Type
WEEKDAY    11151
SAT.        7837
SUN.        7495
Name: count, dtype: int64

In [14]:
prt_clean.isna().sum()

Route                0
Route_Full_Name    202
Current_Garage     194
Mode                 0
Month_Start          0
Date_Key             0
Day_Type             0
Avg_Riders           0
Day_Count            0
dtype: int64

In [15]:
prt_clean.loc[
    prt_clean["Route_Full_Name"].isna() | prt_clean["Current_Garage"].isna(),
    ["Route", "Route_Full_Name", "Current_Garage", "Mode", "Month_Start", "Avg_Riders"]
].head(20)

     Route Route_Full_Name Current_Garage  Mode Month_Start  Avg_Riders
62     99E             NaN   East Liberty   Bus    4/1/2026  979.500000
63     99N             NaN           Ross   Bus    4/1/2026  714.500000
64     99S             NaN   West Mifflin   Bus    4/1/2026  163.000000
65     99W             NaN        Collier   Bus    4/1/2026  604.500000
217    99E             NaN   East Liberty   Bus    4/1/2026  922.727273
218    99N             NaN           Ross   Bus    4/1/2026  602.545455
219    99S             NaN   West Mifflin   Bus    4/1/2026  125.818182
220    99W             NaN        Collier   Bus    4/1/2026  614.590909
2412  MNT1             NaN            NaN  Rail    7/1/2025    0.363636
2901  MNT1             NaN            NaN   Bus    5/1/2025    7.619048
4212  MNT1             NaN            NaN   Bus   11/1/2024    0.200000
5919  MNT1             NaN            NaN   Bus    4/1/2024    6.000000
6072  MNT1             NaN            NaN   Bus    4/1/2024    2.500000
6162  MNT1             NaN            NaN   Bus    3/1/2024    1.400000
6235  MNT1             NaN            NaN   Bus    3/1/2024    5.000000
6316  MNT1             NaN            NaN   Bus    3/1/2024    8.380952
6478  MNT1             NaN            NaN   Bus    2/1/2024    5.250000
6559  MNT1             NaN            NaN   Bus    2/1/2024    0.571429
6648  MNT1             NaN            NaN   Bus    1/1/2024    5.000000
6721  MNT1             NaN            NaN   Bus    1/1/2024    1.000000

In [16]:
prt_clean.loc[
    prt_clean["Route_Full_Name"].isna() | prt_clean["Current_Garage"].isna(),
    "Route"
].value_counts()

Route
68      108
MNT1     75
78        9
99E       2
99N       2
99S       2
99W       2
MNT       2
Name: count, dtype: int64

In [17]:
prt_clean.loc[
    prt_clean["Route"].isin(["68", "MNT1"]),
    ["Route", "Route_Full_Name", "Current_Garage", "Mode", "Month_Start", "Day_Type", "Avg_Riders"]
].head(30)

,Route,Route_Full_Name,Current_Garage,Mode,Month_Start,Day_Type,Avg_Riders
2412,MNT1,NaN,NaN,Rail,7/1/2025,WEEKDAY,0.363636
2901,MNT1,NaN,NaN,Bus,5/1/2025,WEEKDAY,7.619048
4212,MNT1,NaN,NaN,Bus,11/1/2024,SAT.,0.200000
5919,MNT1,NaN,NaN,Bus,4/1/2024,SAT.,6.000000
6072,MNT1,NaN,NaN,Bus,4/1/2024,WEEKDAY,2.500000
6162,MNT1,NaN,NaN,Bus,3/1/2024,SAT.,1.400000
6235,MNT1,NaN,NaN,Bus,3/1/2024,SUN.,5.000000
6316,MNT1,NaN,NaN,Bus,3/1/2024,WEEKDAY,8.380952
6478,MNT1,NaN,NaN,Bus,2/1/2024,SUN.,5.250000
6559,MNT1,NaN,NaN,Bus,2/1/2024,WEEKDAY,0.571429
6648,MNT1,NaN,NaN,Bus,1/1/2024,SAT.,5.000000
6721,MNT1,NaN,NaN,Bus,1/1/2024,SUN.,1.000000
6801,MNT1,NaN,NaN,Bus,1/1/2024,WEEKDAY,3.909091
7373,MNT1,NaN,NaN,Bus,10/1/2023,SAT.,11.750000
7446,MNT1,NaN,NaN,Bus,10/1/2023,SUN.,3.600000
7527,MNT1,NaN,NaN,Bus,10/1/2023,WEEKDAY,3.818182
7859,MNT1,NaN,NaN,Bus,8/1/2023,SAT.,2.000000
7932,MNT1,NaN,NaN,Bus,8/1/2023,SUN.,4.750000
8013,MNT1,NaN,NaN,Bus,8/1/2023,WEEKDAY,0.347826
8176,MNT1,NaN,NaN,Bus,7/1/2023,SUN.,1.166667
9073,MNT1,NaN,NaN,Bus,3/1/2023,SAT.,0.500000
9146,MNT1,NaN,NaN,Bus,3/1/2023,SUN.,0.500000
9227,MNT1,NaN,NaN,Bus,3/1/2023,WEEKDAY,0.173913
9317,MNT1,NaN,NaN,Bus,2/1/2023,SAT.,12.250000
9389,MNT1,NaN,NaN,Bus,2/1/2023,SUN.,12.500000
9469,MNT1,NaN,NaN,Bus,2/1/2023,WEEKDAY,22.000000
9559,MNT1,NaN,NaN,Bus,1/1/2023,SAT.,15.750000
9631,MNT1,NaN,NaN,Bus,1/1/2023,SUN.,4.000000
9711,MNT1,NaN,NaN,Bus,1/1/2023,WEEKDAY,17.818182
9801,MNT1,NaN,NaN,Bus,12/1/2022,SAT.,26.800000

In [18]:
prt_clean.loc[
    prt_clean["Route"] == "68",
    ["Route", "Route_Full_Name", "Current_Garage", "Mode", "Month_Start", "Day_Type", "Avg_Riders"]
].head(20)

,Route,Route_Full_Name,Current_Garage,Mode,Month_Start,Day_Type,Avg_Riders
17682,68,NaN,NaN,Bus,3/1/2020,SAT.,95.250000
17747,68,NaN,NaN,Bus,3/1/2020,SUN.,36.200000
17912,68,NaN,NaN,Bus,2/1/2020,SAT.,409.400000
17974,68,NaN,NaN,Bus,2/1/2020,SUN.,248.500000
18138,68,NaN,NaN,Bus,1/1/2020,SAT.,436.500000
18200,68,NaN,NaN,Bus,1/1/2020,SUN.,231.800000
18363,68,NaN,NaN,Bus,12/1/2019,SAT.,495.750000
18425,68,NaN,NaN,Bus,12/1/2019,SUN.,217.166667
18588,68,NaN,NaN,Bus,11/1/2019,SAT.,483.400000
18650,68,NaN,NaN,Bus,11/1/2019,SUN.,185.200000
18813,68,NaN,NaN,Bus,10/1/2019,SAT.,468.250000
18875,68,NaN,NaN,Bus,10/1/2019,SUN.,292.500000
18950,68,NaN,NaN,Bus,10/1/2019,WEEKDAY,0.130435
19040,68,NaN,NaN,Bus,9/1/2019,SAT.,522.500000
19102,68,NaN,NaN,Bus,9/1/2019,SUN.,301.666667
19176,68,NaN,NaN,Bus,9/1/2019,WEEKDAY,0.850000
19266,68,NaN,NaN,Bus,8/1/2019,SAT.,521.000000
19328,68,NaN,NaN,Bus,8/1/2019,SUN.,287.250000
19492,68,NaN,NaN,Bus,7/1/2019,SAT.,473.250000
19554,68,NaN,NaN,Bus,7/1/2019,SUN.,224.600000

In [19]:
prt_clean[prt_clean["Avg_Riders"] < 0]

,Route,Route_Full_Name,Current_Garage,Mode,Month_Start,Date_Key,Day_Type,Avg_Riders,Day_Count
1637,53,53 - HOMESTEAD PARK,West Mifflin,Bus,10/1/2025,202510,WEEKDAY,-0.826087,23
16370,71,71 - EDGEWOOD TOWN CENTER,East Liberty,Bus,9/1/2020,202009,SUN.,-0.400000,5
16392,P69,P69 - TRAFFORD FLYER,East Liberty,Bus,9/1/2020,202009,SUN.,-0.400000,5
20255,MNT1,NaN,NaN,Bus,4/1/2019,201904,SUN.,-1.000000,4
20309,68,NaN,NaN,Bus,4/1/2019,201904,WEEKDAY,-0.045455,22
20336,MNT1,NaN,NaN,Bus,4/1/2019,201904,WEEKDAY,-1.954545,22
20651,MNT1,NaN,NaN,Bus,2/1/2019,201902,SAT.,-0.750000,4

In [20]:
prt_clean[prt_clean["Day_Count"] <= 0]

Empty DataFrame
Columns: [Route, Route_Full_Name, Current_Garage, Mode, Month_Start, Date_Key, Day_Type, Avg_Riders, Day_Count]
Index: []

In [21]:
prt_clean.loc[prt_clean["Avg_Riders"] < 0, "Avg_Riders"] = pd.NA

In [22]:
prt_clean["Avg_Riders"].isna().sum()

np.int64(7)

In [23]:
prt_clean["Avg_Riders"].describe()

count    26476.000000
mean      1145.860743
std       1321.989074
min          0.000000
25%        328.125000
50%        709.715909
75%       1450.022727
max      11510.250000
Name: Avg_Riders, dtype: float64

In [24]:
prt_clean.nlargest(10, "Avg_Riders")[
    ["Route", "Route_Full_Name", "Mode", "Month_Start", "Day_Type", "Avg_Riders"]
]

,Route,Route_Full_Name,Mode,Month_Start,Day_Type,Avg_Riders
24643,P1,P1 - EAST BUSWAY-ALL STOPS,Bus,9/1/2017,WEEKDAY,11510.25000
21928,P1,P1 - EAST BUSWAY-ALL STOPS,Bus,9/1/2018,WEEKDAY,11380.63158
24658,RED,RED - Castle Shannon via Beechview,Rail,9/1/2017,WEEKDAY,11342.55000
25340,RED,RED - Castle Shannon via Beechview,Rail,6/1/2017,WEEKDAY,11333.45455
25552,P1,P1 - EAST BUSWAY-ALL STOPS,Bus,5/1/2017,WEEKDAY,11277.50000
21702,P1,P1 - EAST BUSWAY-ALL STOPS,Bus,10/1/2018,WEEKDAY,11265.86957
25567,RED,RED - Castle Shannon via Beechview,Rail,5/1/2017,WEEKDAY,11258.50000
19221,RED,RED - Castle Shannon via Beechview,Rail,9/1/2019,WEEKDAY,11221.35000
22623,RED,RED - Castle Shannon via Beechview,Rail,6/1/2018,WEEKDAY,11168.85714
19673,RED,RED - Castle Shannon via Beechview,Rail,7/1/2019,WEEKDAY,11166.63636

In [25]:
prt_clean[["Month_Start", "Date_Key"]].head(10)

  Month_Start  Date_Key
0    4/1/2026    202604
1    4/1/2026    202604
2    4/1/2026    202604
3    4/1/2026    202604
4    4/1/2026    202604
5    4/1/2026    202604
6    4/1/2026    202604
7    4/1/2026    202604
8    4/1/2026    202604
9    4/1/2026    202604

In [26]:
prt_clean["Month_Start"] = pd.to_datetime(prt_clean["Month_Start"])

In [27]:
prt_clean["Month_Start"].dtype

dtype('<M8[us]')

In [28]:
prt_clean["Year"] = prt_clean["Month_Start"].dt.year

In [29]:
prt_clean[["Month_Start", "Year"]].head(10)

  Month_Start  Year
0  2026-04-01  2026
1  2026-04-01  2026
2  2026-04-01  2026
3  2026-04-01  2026
4  2026-04-01  2026
5  2026-04-01  2026
6  2026-04-01  2026
7  2026-04-01  2026
8  2026-04-01  2026
9  2026-04-01  2026

In [30]:
prt_clean["Year"].value_counts().sort_index()

Year
2017    2723
2018    2714
2019    2721
2020    2773
2021    2908
2022    2907
2023    2911
2024    2923
2025    2927
2026     976
Name: count, dtype: int64

In [31]:
prt_clean.groupby("Year")["Month_Start"].nunique()

Year
2017    12
2018    12
2019    12
2020    12
2021    12
2022    12
2023    12
2024    12
2025    12
2026     4
Name: Month_Start, dtype: int64

In [45]:
prt_clean.to_csv("Data/prt_monthly_ridership_clean.csv", index=False)

In [46]:
clean_check = pd.read_csv("Data/prt_monthly_ridership_clean.csv")
clean_check.shape

(26483, 10)

In [47]:
(clean_check["Avg_Riders"] < 0).sum()

np.int64(0)